services:
  - type: web
    name: agenda-tarefas-api
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py migrate
    startCommand: cd backend && gunicorn setup.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: agenda-tarefas-api.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://agenda-tarefas-web.onrender.com
      - key: FRONTEND_URL
        value: https://agenda-tarefas-web.onrender.com

  - type: static_site
    name: agenda-tarefas-web
    staticPublishPath: frontend/dist
    buildCommand: cd frontend && npm install && npm run build
    envVars:
      - key: VITE_API_BASE_URL
        value: https://agenda-tarefas-api.onrender.com/api/
